/**
 * Module for constants variabes and enums
 * @module Constants
 */

/**
 * array of all 88 keys to help determine if specific key is black (1) or white (0)
 */
const keyNotes = [0, 1, 0];
for (let i = 0; i < 7; i++) {
    keyNotes.push(0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0);
}
keyNotes.push(0);
export { keyNotes };

export const oscillatorTypes = ['sine', 'square', 'sawtooth', 'triangle'];

/**
 * array of all 88 frequencies for each note starting from a0
 */
const keyFrequencies = [27.5];
const multipler = Math.pow(2, 1 / 12);
for (let i = 1; i < 89; i++) {
    keyFrequencies.push(keyFrequencies[i - 1] * multipler);
}
export { keyFrequencies };

/**
 * object containing all available note lengths
 */
export const noteLengths = {
    fullNote: { name: '1/1', id: 0 },
    halfNote: { name: '1/2', id: 1 },
    quarterNote: { name: '1/4', id: 2 },
    eighthNote: { name: '1/8', id: 3 },
    sixteenthNote: { name: '1/16', id: 4 },
};

/**
 * object containing all available tools
 */
export const tools = {
    draw: { name: 'Draw', id: 0 },
    select: { name: 'Select', id: 1 },
    remove: { name: 'Remove', id: 2 },
    copyPaste: { name: 'Copy / Paste', id: 3 },
};

/**
 * object constaining all available instruments
 */
export const Instruments = {
    Sampler: { name: 'Sampler', id: 0 },
    PqSynth: { name: 'PqSynth', id: 1 },
    Monotron: { name: 'Monotron', id: 2 },
    MultiOsc: { name: 'MultiOsc Synth', id: 3 },
};

export enum PluginsEnum {
    Compressor,
    Equalizer,
    Distortion,
    Delay,
    Reverb,
    Chorus,
}

export const Plugins = [
    {
        name: 'Compressor',
        id: PluginsEnum.Compressor,
    },
    {
        name: 'Equalizer',
        id: PluginsEnum.Equalizer,
    },
    {
        name: 'Distortion',
        id: PluginsEnum.Distortion,
    },
    {
        name: 'Delay',
        id: PluginsEnum.Delay,
    },
    {
        name: 'Reverb',
        id: PluginsEnum.Reverb,
    },
    {
        name: 'Chorus',
        id: PluginsEnum.Chorus,
    },
];

/**
 * enum of update actions
 */
export const updateActions = {
    solo: 0,
    mute: 1,
    recotd: 2,
    add: 3,
    remove: 4,
};

/**
 * enum of available track types
 */
export const TrackTypes = {
    virtualInstrument: 0,
    audio: 1,
    aux: 2,
};

/**
 * enum for determining how to handle stopping sound
 */
export const SoundOrigin = {
    composition: 0, //Sounds scheduled by sequencer
    pianoRollNote: 1, //Sounds generated by tweaking pianoRoll
    keyboard: 2, //Sounds generated by playing on keyboard
};

/**
 * Keyboard key geometry (Stage 11 — 42px inset re-skin).
 *
 * `keyboardWidths[i].startWidth` is the left offset (in real px) of key i, in the
 * same coordinate system as `.whiteKey`'s CSS `width` and `keyboard.width`
 * (= ComposingCol.offsetWidth). Whites flow via CSS float at WHITE_KEY_WIDTH;
 * blacks are absolutely positioned by their startWidth delta. Because all three
 * (this table, the CSS widths, and the Keyboard.jsx offsets) share one unit,
 * scaling every geometry constant by the SAME factor is a pure horizontal zoom:
 * black/white alignment is preserved exactly, only the physical key size shrinks
 * (so more octaves fit the unchanged container width). The source numbers below
 * are the original 66px-key layout; KEYBOARD_SCALE maps them to the 42px design.
 */
export const WHITE_KEY_WIDTH = 46;
const ORIG_WHITE_KEY_WIDTH = 66;
const KEYBOARD_SCALE = WHITE_KEY_WIDTH / ORIG_WHITE_KEY_WIDTH;
// Reserved left offset before the first octave (left option key + slack); the
// range/scroll math in Keyboard.jsx subtracts this from the container width.
export const KEYBOARD_BASE_OFFSET = Math.round(122 * KEYBOARD_SCALE);
const OCTAVE_WIDTH = Math.round(462 * KEYBOARD_SCALE); // 7 white keys

// How many octaves the (now fixed-size, inset/centered) keyboard shows at once.
export const KEYBOARD_VISIBLE_OCTAVES = 2;
// Fixed render width (px). The keyboard shows a constant ~2-octave span centered in
// the composing area, independent of its width — the render/clamp math in
// Keyboard.jsx uses this as `keyboard.width` (budget = this - KEYBOARD_BASE_OFFSET),
// replacing the old ComposingCol.offsetWidth coupling.
export const KEYBOARD_VIEW_WIDTH = KEYBOARD_VISIBLE_OCTAVES * OCTAVE_WIDTH + KEYBOARD_BASE_OFFSET;

const keyboardWidths = [
    { sharp: false, startWidth: 0 },
    { sharp: true, startWidth: Math.round(47 * KEYBOARD_SCALE) },
    { sharp: false, startWidth: WHITE_KEY_WIDTH },
];
// per-octave (C..B) source offsets at the original 66px scale
const octaveKeysWidth = [0, 55, 66, 123, 122, 198, 254, 264, 322, 330, 389, 396];
const octaveKeysSharp = [false, true, false, true, false, false, true, false, true, false, true, false];
for (let i = 0; i < 7; i++) {
    for (let j = 0; j < 12; j++) {
        keyboardWidths.push({
            sharp: octaveKeysSharp[j],
            startWidth: Math.round(octaveKeysWidth[j] * KEYBOARD_SCALE) + KEYBOARD_BASE_OFFSET + i * OCTAVE_WIDTH,
        });
    }
}
keyboardWidths.push({ sharp: false, startWidth: keyboardWidths[86].startWidth + WHITE_KEY_WIDTH });
export { keyboardWidths };

/**
 * List of strings representing each of 88 notes musical notation for displaying purpose
 */
const keys = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
const defaultKeysNames = ['A0', 'A#0', 'B0'];
for (let i = 0; i < 7; i++) {
    for (let j = 0; j < keys.length; j++) {
        defaultKeysNames.push(keys[j] + (i + 1).toString());
    }
}
defaultKeysNames.push('C8');
export { defaultKeysNames };

const defaultKeysNamesNoOctaveNumber = ['A', 'A#', 'B'];
for (let i = 0; i < 7; i++) {
    for (let j = 0; j < keys.length; j++) {
        defaultKeysNamesNoOctaveNumber.push(keys[j]);
    }
}
defaultKeysNamesNoOctaveNumber.push('C');

export { defaultKeysNamesNoOctaveNumber };

// Two-octave computer-keyboard piano, C-based (FL-style): the upper row is the
// low octave and the lower row the high octave, chromatic C→B in each, with the
// number keys (2 3 5 6 7) and s d g h j falling on the black notes. Index i here
// is also KEY_TO_INDEX[key] in Keyboard.jsx — keep the two in the same order.
export const keyboardKeyOrder = [
    'q',
    '2',
    'w',
    '3',
    'e',
    'r',
    '5',
    't',
    '6',
    'y',
    '7',
    'u', // C3..B3
    'z',
    's',
    'x',
    'd',
    'c',
    'v',
    'g',
    'b',
    'h',
    'n',
    'j',
    'm', // C4..B4
];
// Bindings start at C3 (MIDI 48) = the default first visible key, so the on-key
// shortcut labels line up with the visible keys. Octave-shift keeps them in sync.
export const defaultKeyBindings = keyboardKeyOrder.map((keyboardKey, i) => ({ MIDINote: 48 + i, keyboardKey }));
