# fly.toml app configuration file generated for pqsound on 2023-05-28T23:08:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pqsound"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
